name: app_eduardo
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^9.2.0
  responsive_table: ^0.2.0+2
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets: 
    - assets/back1.jpg
    - assets/back2.jpg
    - assets/imagemAbout.png
    - assets/pel1.jpg
    - assets/pel2.jpg
    - assets/pel3.jpg
    - assets/pel4.jpg
    - assets/pel5.jpg
    - assets/pel6.jpg
    - assets/pel7.jpg
  uses-material-design: true

